clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      tags: true

steps:
  - name: build
    image: bitnami/git:latest
    commands:
      - apt-get update && apt-get install -y xmlstarlet
      - bash /home/niko/scripts/1.2_buildLinux64.sh
  - name: appimage
    image: debian:bookworm
    commands:
      - bash /home/niko/scripts/1.5_buildAppImage.sh
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: garlic-signage.com
      username: niko
      key:
        from_secret: GarlicSignageKey
      script:
        - bash /home/niko/deploy.sh
